version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=saasproj

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=saasproj
      - USE_DOCKER=yes
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    links:
      - postgres
